title:            Tom Bevers
description:      Personal blog of Tom Bevers
url:              http://tombevers.me
markdown:         kramdown
highlighter:         true
permalink:        /:year/:month/:day/:title
# Owner/author information
owner:
  name:           Tom Bevers
  firstname:      Tom
  lastname:       Bevers
  email:          hello@tombevers.me
  # Social networking links used in footer.
  twitter:        tombevers
  github:         tombevers
  stackexchange:  http://stackexchange.com/users/29819/tom
  linkedin:       tombevers
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/1/118427252518503055068
  
# Analytics and webmaster tools stuff goes here
google_analytics:   UA-2215924-9
google_verify:      PdjFBJSPteDgaL5cSuupwFTVs7ko2JA-yKM2_pfr8cs

# Diqus account for comments
disqus: tombevers

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Contact
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Brussels
future:      false

exclude: ['less']
